# **RBOT 250 Robot Manipulation, Planning and Control**

## Assignment 2: Rigid Body Motions

#### Instructor: Dr. Lekan Molu

#### Submitted By: Salinee Kingbaisomboon (Sage ID: 20801897)

---

### Given an axis of motion, w = [0, 0, 1] and a rotation angle of 45 degrees, write a python script that computes the exponential map of the rotation angle using Rodrigue's formula

In [7]:
### Answer
import numpy as np

w = np.array([0,0,1]) # axis of motion
angle = np.pi/4 # rotation angle of 45 degrees
exponential_map = np.identity(3) + w*angle + (1 - np.cos(angle))*(w*np.transpose(w)) # This euqation is based on the (3.2.6) on Murray's textbook

# Display the exponential map
print(exponential_map)

[[1.         0.         1.07829138]
 [0.         1.         1.07829138]
 [0.         0.         2.07829138]]
